trigger:
- main

stages:
- stage: Build
  displayName: 'Build and Test Stage'
  jobs:
    - job: BuildJob
      displayName: 'Compile Java and Run Tests'
      pool:
        vmImage: 'ubuntu-latest'

      services:
        postgres:
          image: postgres:13
          env:
            POSTGRES_USER: $(postgresUser)
            POSTGRES_PASSWORD: $(postgresPassword)
            POSTGRES_DB: $(postgresDB)
          ports:
            - 5432:5432

      steps:
        - task: AzureKeyVault@2
          name: FetchSecrets
          inputs:
            azureSubscription: 'Keys'  
            KeyVaultName: 'mtcgSecrets'
            SecretsFilter: '*'
            RunAsPreJob: true

        - script: |
            echo "Waiting for PostgreSQL to be ready..."
            sleep 10
          displayName: 'Wait for DB'

        - task: Maven@3
          inputs:
            mavenPomFile: 'MTCG/pom.xml'
            goals: 'package'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            workingDirectory: 'MTCG'
          env:
            DB_USER: $(postgresUser)
            DB_PASS: $(postgresPassword)
            DB_NAME: $(postgresDB)
            DB_HOST: 'localhost'
            DB_PORT: $(dbPort)

        - task: Maven@3
          inputs:
            mavenPomFile: 'MTCG/pom.xml'
            goals: 'test'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            workingDirectory: 'MTCG'
          displayName: 'Run JUnit Tests'
          env:
            DB_USER: $(postgresUser)
            DB_PASS: $(postgresPassword)
            DB_NAME: $(postgresDB)
            DB_HOST: 'localhost'
            DB_PORT: $(dbPort)

- stage: Release
  displayName: 'Release Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: PushToDockerHub
      displayName: 'Build Docker Image and Push to Docker Hub'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: AzureKeyVault@2
          name: FetchDockerSecrets
          inputs:
            azureSubscription: 'Keys'  
            KeyVaultName: 'mtcgSecrets'
            SecretsFilter: 'dockerUsername,dockerAccessToken'
            RunAsPreJob: true

        - task: Docker@2
          displayName: 'Build and Push Docker Image'
          inputs:
            containerRegistry: 'DockerHubServiceConnection'  
            repository: '$(dockerUsername)/mtcg'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              latest
