@startuml

package org.mtcg {

class User {
        - String username
        - String password
        - int coins
        - List<Card> stack
        - List<Card> deck
        + static List<User> users

        + User(String username, String password)
        + int getCoins()
        + void setCoins(int coins)
        + static List<User> getUsers()
        + static void setUsers(List<User> users)
        + String getUsername()
        + String getPassword()
        + String toString()
        + List<Card> getStack()
        + void setStack(List<Card> stack)
        + List<Card> getDeck()
        + void setDeck(List<Card> deck)
    }

  class Package {
      - List<Card> cards

      + Package()
      + Package(List<Card> cards)
      + List<Card> getCards()
    }

    Package --> "1..*" Card : contains

    class Server {
      - static int port

      + Server(int port)
      + static void start()
      + static void handleClient(Socket clientSocket)

      - void handlePOSTRequest(String requestLine, BufferedReader in, OutputStream out)
    }

    Server --> "1..*" User : manages

    class Main {
        + static void main(String[] args)
    }

Main --> Server : starts

class Card {
        + static final String SPELL_CARD
        + static final String MONSTER_CARD
        - String name
        - int damage
        - String elementType
        - String cardType

        + Card(String name, int damage, String elementType, String cardType)
        + String getCardType()
        + void setCardType(String cardType)
        + String getName()
        + void setName(String name)
        + int getDamage()
        + void setDamage(int damage)
        + String getElementType()
        + void setElementType(String elementType)
    }

}

@enduml
